### ISSUE TITLE
Migration of old developer docs [TODO]

### ISSUE THREAD

**Issue by drojf** [07th-mod/wiki#40]
- [x] Migrate developer wiki https://github.com/07th-mod/higurashi-dev-guides
 - [ ] Double check the old github hosted developer wiki doesn't contain any additional pages here: https://github.com/07th-mod/higurashi-dev-guides/wiki
 - [ ] Migrate github hosted higurashi-patch-compiler wiki: https://github.com/07th-mod/higurashi-patch-compiler/wiki
